# Setup
title:               Kevin Takano 
tagline:             'takano'
description:         'A personal blog about programming.'
url:                 //takanovcs.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kevin Takano
  url:               //www.linkedin.com/in/kevin-takano-b8ab9bb4/
  email:             kevin.takano@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

gravatar_md5: 7406ff0b98ddadc44c1dee35cb12fac8
