# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:            Code-Flava
tagline:          'Programming school'
description:      'Just a personal blog with programming tips mainly using python for basic algorithms and basic machine learning concepts. Our objective it is to create useful and easy articles to our readers.'
url:              http://takanovcs.github.io
baseurl:          /

author:
  name:           'Kevin Takano'
  url:            https://www.linkedin.com/in/kevin-takano-b8ab9bb4/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
